### ISSUE TITLE
Codelens doesn't work on some references, eg abstract Thing definitions

### ISSUE THREAD

**Issue by Wolfsblvt** [zzzz465/rwxml-language-server#128]
Creating it's own issue based on my observation in #119.

My own abstract def has no quick info line above. Should show that it is referenced once. Checking other mods that work as well none of the abstract defs have that line above.  
Go to references on the abstract def doesn't work
 
> quick info is called "CodeLens". anyway, the reason why it's broken is a bit complex. there's two refernce types, 1. `<defName>`, 2. `Name` attribute. language server manages both types on resolving, but some features supports only one. that's why it doesn't pop up quick info.
> 
> you can see [codelens code here](https://github.com/zzzz465/rwxml-language-server/blob/7c5ac82fcd77ca3d282d06895daa780dfa057a04/language-server/src/features/codeLens.ts#L33-L53) as you can see, it checks `<defName>` value to determine whether to display codelens or not.
> 
> it is not a intended feature and needs to be fix.

**Comment by zzzz465** [comment]
![image](https://user-images.githubusercontent.com/46273764/172006057-53b087b6-a83f-48d6-a404-56e694f7a544.png)

PR #135 will be included in the next version release.
