### ISSUE TITLE
Codelens shows up multiple times for definitions in some files

### ISSUE THREAD

**Issue by Wolfsblvt** [zzzz465/rwxml-language-server#129]
Creating it's own issue based on my observation in #119.

![image](https://user-images.githubusercontent.com/9962104/170846187-32c81da3-59ec-4c97-aaea-0e185aa5ef76.png)

I opened a few workshop mods that I downloaded to test the features of this extension, and to dive a bit deeper into some of their code.  
For a few, the Codelens info on the definitions showed up four times, not the usual 1 time which I saw in most other places.  
I guess this is not intended?

I can provide the link to the workshop mod from the screenshot: [Door Mat](https://steamcommunity.com/sharedfiles/filedetails/?id=1505423207)  
I can also post the files or more info if you need it.

**Comment by zzzz465** [comment]
did you opened your own mod's workspace and open doormat's file?
or did you open doormat mod as workspace?

**Comment by zzzz465** [comment]
the reason why it displays multiple times because `<Defs>` is loaded on various versions.

- 1.0
- 1.1
- 1.2
- 1.3

so there's 4 of them.

**Comment by zzzz465** [comment]
maybe I should add version as prefix if multiple projects are involved.

**Comment by Wolfsblvt** [comment]
I went to the root folder of the mod, SHIFT right-clicked in windows and opened the whole mod folder as a workspace in VSCode. 
 
So yes, all those folders were there.  
I think i get why this is happening, yeah.

I am actually not sure what the best way to display this would be. I can't think of a reason right now where I would prefer references from different versions be displayed separately. Grouping them should be fine, and still clear when you open the popup to see where those references are.

**Comment by zzzz465** [comment]
given that the file location is displayed on preview window, I think merging results would be nice.

![image](https://user-images.githubusercontent.com/46273764/170897828-79627a4f-26db-4711-b673-e4f523d0b46b.png)

this is an image when opening `hediffs_global_needs.xml` from core when `Anty` mod is workspace.
you can see that all of them referencing the same node but multiple codelens is displayed. and I think it should be merged.

**Comment by Wolfsblvt** [comment]
Makes sense to me, agreed. That's a good example.

**Comment by Wolfsblvt** [comment]
Nice, thank you!
