### ISSUE TITLE
Paths: Workshop Mods settings is ignored

### ISSUE THREAD

**Issue by LegendaryGeek** [zzzz465/rwxml-language-server#131]
the setting of Paths: Workshop Mods is ignored, and it will always use the standard default path. as shown here: 
![image](https://user-images.githubusercontent.com/45850917/171972330-87d42970-d2dd-494d-af17-9a20668ed699.png)

**Comment by zzzz465** [comment]
@LegendaryGeek 
it's fixed in PR #133 and it'll be applied in the next version.
![image](https://user-images.githubusercontent.com/46273764/171989178-823b9d5b-e4c3-4388-b92c-b97f43b48410.png)
