### ISSUE TITLE
Can't find or install this extension

### ISSUE THREAD

**Issue by sTiKyt** [zzzz465/rwxml-language-server#2]
![image](https://user-images.githubusercontent.com/35602029/96910768-7de57280-148f-11eb-910c-3ceacdc7c48e.png)

Is it Windows-only? Is Linux planned to be supported?

**Comment by zzzz465** [comment]
try search "rwxml" only, it should appear on the top.

**Comment by sTiKyt** [comment]
![image](https://user-images.githubusercontent.com/35602029/97241018-c088b100-17e7-11eb-80eb-271aa40bafb4.png)

**Comment by zzzz465** [comment]
maybe I uploaded it as windows-only. it won't take too long to fix.
before that, try installing extension via vsix package
1. clone the repo and build it manually or
2. download
https://drive.google.com/file/d/1epr6Dpg4NZ1c8ERjySYgXUd7bXf59aVa/view?usp=sharing 
this is the latest vsix build (vsix file are not allowed to upload on Github)

**Comment by sTiKyt** [comment]
Does .vsix automatically detect updates,etc or i'll need to reinstall it after problem is fixed?

**Comment by sTiKyt** [comment]
Well it requires some .exe file, so i guess IT IS Windows only
![image](https://user-images.githubusercontent.com/35602029/97480033-cb0f8b80-194a-11eb-966e-cc9e972a9780.png)

**Comment by sTiKyt** [comment]
Or, maybe, vsix package you sent was windows only?

**Comment by zzzz465** [comment]
oh, the type extractor is built only for windows I guess.
it's was built with net framework 4.7 so it may require some code changes in order to make it work on Linux

**Comment by sTiKyt** [comment]
Why not use mono or something?

**Comment by zzzz465** [comment]
I didn't expect Linux users to use this, also I'm looking forward to using NET 5 instead of mono. 
NET 5 just released a couple of days ago so it takes some time to apply new things to the code.
I'll ping you and re-open this ticket when the rework is done. (December maybe)

**Comment by sTiKyt** [comment]
Yeah, just keep in mind that Rimworld officially supports Linux distros, so modding on Linux exists as well

**Comment by sTiKyt** [comment]
Done? xD

**Comment by zzzz465** [comment]
I started working on this bug... so what I've figured out until now is
1. Net 5 (net core) cannot load assembly by reflection only (since it's NET core, not framework it cannot load it directly)
2. I tried to run extractor on Linux with mono, but somehow it isn't working.

need more study I guess?

**Comment by zzzz465** [comment]
@sTiKyt experimental version is now available for Linux.
tested in Ubuntu 20.0.4 (LTS) in hyper-v session.
since it is not uploaded to extension yet, you can download the installation file below or you can clone the dev branch and build it yourself.

also, it includes a GUI update for the config file which is not stable for now, so if you encounter any bug, please switch to text editor and type values manually.

[rwxml-lang-serv-0.4.27.zip](https://github.com/zzzz465/rwxml-language-server/files/5723343/rwxml-lang-serv-0.4.27.zip)

**Comment by zzzz465** [comment]
@sTiKyt we now have version 0.4.28 which includes tons of updates, including Linux support + GUI support, Webpack optimization.
I'm asking you to test the new version on your desktop to check it is working well on Linux.
after your check, I'll close this issue.

**Comment by RobRoseKnows** [comment]
I was unable to install it on MacOS, I don't have Rimworld installed on this computer though so I didn't test if it actually worked.

**Comment by sTiKyt** [comment]
@zzzz465 i don't have rimworld/vscode installed right now, but if it worked on ubuntu i'm sure you can close it already
