### ISSUE TITLE
How to set up 1.3 Insider version.

### ISSUE THREAD

**Issue by Epicguru** [zzzz465/rwxml-language-server#62]
Hello! Thank you for making this tool. I found it very useful in the past.

I was hoping for a quick guide to setting up the new Insider version. I have installed it in VSCode but it does not seem to do anything. More specifically, it does not seem to recognize my custom def types or fields.
I understand that it no longer uses the config file (?)
Any help getting it to work would be appreciated.

I would like to help test and give feedback.
Thank you.

**Comment by zzzz465** [comment]
there's no reason to leave an old master version so I moved the insider version to the master version.

you don't have to configure anything (v0.10.0 or up)
the extension requires `RimWorld DLL`, `RimWorld Core` to run, and it scans steam workshop, local mods/ directory for external mod support.

the default values are below

RimWorld DLL
- windows: `C:\Program files (x86)\Steam\steamapps\common\rimworld\RimWorldWin64_Data\Managed`
- darwin(macos): `Library/Application Support/Steam/steamapps/common/RimWorld/RimWorldMac.app/Contents/Resources/Data/Managed`

RimWorld Core
- windows: `C:\\Program Files (x86)\\Steam\\steamapps\\common\\RimWorld\\Data`
- darwin(macos): `Library/Application Support/Steam/Steamapps/common/RimWorld/RimWorldMac.app/Data`

Local Mod Directory
- windows: `C:\\Program Files (x86)\\Steam\\steamapps\\common\\RimWorld\\Mods`
- darwin(macos): `Library/Application Support/Steam/Steamapps/common/RimWorld/RimWorldMac.app/Mods`

Workshop Directory
- windows: `C:\\Program Files (x86)\\Steam\\steamapps\\workshop\\content\\294100`
- darwin(macos): `Library/Application Support/Steam/Steamapps/workshop/content/294100`

unfortunately, customizing this path is not supported yet.

**Comment by Epicguru** [comment]
Thank you for explaining. I've tested some more, and it seems that Vanilla defs are working (they have code completion and suggestions) but my custom defs do not:
![image](https://user-images.githubusercontent.com/26253331/153181816-a625a0db-19cc-4efb-8568-e29d6c1fac58.png)

![image](https://user-images.githubusercontent.com/26253331/153181832-e0e4f31f-a498-4473-b232-48963f3a88fb.png)

**Comment by zzzz465** [comment]
external mod def is supported by runtime extraction, and it needs about.xml for mod dependency otherwise it tries to extract def from entire mods, leading to a huge(?) performance drop.

in the past, I managed this dependency as a config file, but as most users aren't familiar with this setup, I ended up using dependencies from about.xml.

if you really want to debug it, you can build the TypeInfo extractor by yourself and do a test against your dll.
I'll write instructions if you need them.

**Comment by zzzz465** [comment]
if you pass me your current Mod project (I suggest github) then I'll check why it's happening

also About/About.xml must be visible on your file view. because it uses vscode's FILE I/O to Read/Watch and it's limited to your current opened directory. don't open just a single xml file, open your mod project with "Open Folder"

**Comment by zzzz465** [comment]
I also found that external mod's def is not supported.
I guess something is broken. I'll fix it

**Comment by zzzz465** [comment]
@Epicguru  I think fixing the project is completed.
as version v0.11.0 has been released, you can try it out.

**Comment by zzzz465** [comment]
I found that autocomplete not working correctly, fixing it.

**Comment by zzzz465** [comment]
@Epicguru version 0.13.0 released. try it out.

**Comment by zzzz465** [comment]
@Epicguru please close the issue if you aren't having any issues.

**Comment by Epicguru** [comment]
I did some quick testing yesterday with .13 and it still didn't seem to work unfortunately. I can send over the mod if you're willing to look into it.

**Comment by zzzz465** [comment]
@Epicguru

## The easy fix
add `loadfolders.xml` in your project with this content.
```xml
<?xml version="1.0" encoding="utf-8" ?>
<loadFolders>
  <v1.3>
    <li>.</li>
  </v1.3>
</loadFolders>
```

## explanation
as the extension supports multi Rimworld version support (v1.0, v1.1, v1.2 ...etc), program must know which version the file belongs. it checks `LoadFolders.xml`, and if exists, follow that rule. if doesn't, the program will try everything useful to get version information. for example, you have assmblies/ resources under `1.3` directory, and the files will be determined as v1.3 project resources. however, `Defs/` directory are not under `1.3` directory, it is determined as `default` (aka fallback)` version.

the program should include all resources in project if there's no `loadfolders.xml`, but somehow it didn't so this is a bug. it'll fixed as soon as possible.

**Comment by Epicguru** [comment]
Ah I see a simple fix then! Thank you very much. I'll close the issue now as it is working now.

This extension will be very useful to be.
