### ISSUE TITLE
1.3 update and Ideology support

### ISSUE THREAD

**Issue by Violet-Vibes** [zzzz465/rwxml-language-server#8]
As 1.3 was released with the Ideology DLC, I'd love to see support for both of these.

**Comment by zzzz465** [comment]
@Violet-Vibes
I'm working new version of this project with a fully refactored, concrete base.
the new version will work without any annoying configuration. (rwconfigrc.json)
now the project has an insider version, so you can easily get the latest developing feature.

https://marketplace.visualstudio.com/items?itemName=madeline.rwxml-language-server-insider
